packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.62.11
  "@radix-ui/react-icons": ^1.3.0
  hono: ^4.6.14
  eslint: ^9.15.0
  prettier: ^3.4.2
  tailwindcss: 3.4.17
  typescript: ^5.6.2
  zod: ^3.24.0
  better-auth: ^1.0.0
  lucide-react: ^0.468.0
  


catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1