packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5.7.3
  zod: ^4.0.15

catalogs:
  react19:
    "react": 19.0.0
    "react-dom": 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
